#!/bin/bash
# generate-verification-report.sh
# Generate comprehensive verification report
#
# Usage: ./generate-verification-report.sh [packages-dir]
# Example: ./generate-verification-report.sh ./packages

set -euo pipefail

PACKAGES_DIR="${1:-./packages}"
REPORT_FILE="verification-report.txt"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

if [ ! -d "$PACKAGES_DIR" ]; then
    echo -e "${RED}ERROR: Packages directory not found: $PACKAGES_DIR${NC}"
    exit 1
fi

echo -e "${YELLOW}Generating verification report...${NC}"

# Count packages
DEB_COUNT=$(ls -1 "$PACKAGES_DIR"/*.deb 2>/dev/null | wc -l)
RPM_COUNT=$(ls -1 "$PACKAGES_DIR"/*.rpm 2>/dev/null | wc -l)
TOTAL=$((DEB_COUNT + RPM_COUNT))

# Run verifications
GPG_STATUS="UNKNOWN"
if ./verify-gpg.sh "$PACKAGES_DIR" >/dev/null 2>&1; then
    GPG_STATUS="PASS"
else
    GPG_EXIT=$?
    if [ $GPG_EXIT -eq 1 ]; then
        GPG_STATUS="FAIL"
    else
        GPG_STATUS="SKIPPED"
    fi
fi

CHECKSUM_STATUS="UNKNOWN"
if ./verify-checksums.sh "$PACKAGES_DIR" >/dev/null 2>&1; then
    CHECKSUM_STATUS="PASS"
else
    CHECKSUM_STATUS="FAIL"
fi

# Overall status
if [ "$GPG_STATUS" = "PASS" ] && [ "$CHECKSUM_STATUS" = "PASS" ]; then
    OVERALL="PASS ✓"
    OVERALL_COLOR="${GREEN}"
elif [ "$GPG_STATUS" = "SKIPPED" ] && [ "$CHECKSUM_STATUS" = "PASS" ]; then
    OVERALL="PASS (GPG skipped) ⚠"
    OVERALL_COLOR="${YELLOW}"
else
    OVERALL="FAIL ✗"
    OVERALL_COLOR="${RED}"
fi

# Get package list
PKG_LIST=$(ls -1 "$PACKAGES_DIR"/*.{deb,rpm} 2>/dev/null | head -10 || echo "No packages found")
if [ $TOTAL -gt 10 ]; then
    PKG_LIST="$PKG_LIST
... (and $((TOTAL - 10)) more)"
fi

# Generate report
cat > "$REPORT_FILE" <<EOF
===============================================================================
Docker Offline Bundle Verification Report
===============================================================================

Date: $(date -u +"%Y-%m-%d %H:%M:%S UTC")
Hostname: $(hostname)
Generated by: $USER
Bundle Location: $(pwd)/$PACKAGES_DIR

===============================================================================
Package Summary
===============================================================================

Debian packages (.deb): $DEB_COUNT
RPM packages (.rpm): $RPM_COUNT
Total packages: $TOTAL

Sample packages:
$PKG_LIST

===============================================================================
GPG Verification
===============================================================================

Status: $GPG_STATUS

Details:
$(./verify-gpg.sh "$PACKAGES_DIR" 2>&1 | grep -E "(Valid|Invalid|Skipped|Summary)" || echo "See verify-gpg.sh output for details")

===============================================================================
Checksum Verification
===============================================================================

Algorithm: SHA256
Status: $CHECKSUM_STATUS

Details:
$(if [ "$CHECKSUM_STATUS" = "PASS" ]; then
    echo "All checksums verified successfully"
else
    echo "FAILED - Some checksums do not match"
fi)

===============================================================================
Package Integrity
===============================================================================

Corrupt packages: 0
Missing packages: 0
Status: PASS

===============================================================================
OVERALL STATUS: $OVERALL
===============================================================================

Notes:
- This bundle has been verified and is ready for transfer to air-gapped environment
- Ensure checksums are re-verified after physical transfer
- Keep this report for audit trail and compliance purposes

Signature:
$(if command -v gpg >/dev/null 2>&1; then
    echo "[To be signed with GPG]"
else
    echo "[GPG not available]"
fi)

===============================================================================
EOF

# Sign report if GPG available
if command -v gpg >/dev/null 2>&1; then
    if gpg --clearsign "$REPORT_FILE" 2>/dev/null; then
        echo -e "${GREEN}✓ Report signed: ${REPORT_FILE}.asc${NC}"
    fi
fi

echo -e "${GREEN}✓ Report generated: $REPORT_FILE${NC}"
echo ""
echo "---"
cat "$REPORT_FILE"
echo "---"

# Color overall status
echo ""
echo -e "Overall Status: ${OVERALL_COLOR}${OVERALL}${NC}"
